<?php if(Mage::getStoreConfig('webfrnd_quickcontact_options/general/module_enable')): ?>

<?php 

	$use_jquery = Mage::getStoreConfig('webfrnd_quickcontact_options/general/jquery') ; 

	$bg_image = Mage::getStoreConfig('webfrnd_quickcontact_options/general/logoimage') ? Mage::getBaseUrl('media') . 'admin-config-uploads/'. Mage::getStoreConfig('webfrnd_quickcontact_options/general/logoimage') : ''; 

	$popup_width = Mage::getStoreConfig('webfrnd_quickcontact_options/general/box_width') ? Mage::getStoreConfig('webfrnd_quickcontact_options/general/box_width').'px' : '580px'; 
	$popup_height = Mage::getStoreConfig('webfrnd_quickcontact_options/general/box_height') ? Mage::getStoreConfig('webfrnd_quickcontact_options/general/box_height').'px' : '350px';
	
	$form_left_margin = Mage::getStoreConfig('webfrnd_quickcontact_options/general/form_left_margin') ? Mage::getStoreConfig('webfrnd_quickcontact_options/general/form_left_margin').'px' : '0px'; 
	$form_top_margin = Mage::getStoreConfig('webfrnd_quickcontact_options/general/form_top_margin') ? Mage::getStoreConfig('webfrnd_quickcontact_options/general/form_top_margin').'px' : '0px';


?>



<script>$_SKIN_URL = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/default/webfrnd/';?>';</script>
<?php if($use_jquery) : ?>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/webfrnd/quickContact/jquery.js'?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/webfrnd/quickContact/jquery_noconflict.js'?>" type="text/javascript"></script>
<?php endif; ?>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/webfrnd/quickContact/modalwindow.js'?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'js/webfrnd/quickContact/quickContact.js'?>" type="text/javascript"></script>

<script>
document.onkeydown = function(e){ 	
				if (e == null) { // ie
					keycode = event.keyCode;
				} else { // mozilla
					keycode = e.which;
				}
				if(keycode == 27){ // close
					jQuery('#dialog .close').trigger('click');
				} 	
			};
</script>

<?php if (Mage::getStoreConfig('webfrnd_quickcontact_options/general/autoload_after') > 0) :?>
<script>
function createCookie(name,value,minutes) {
    if (minutes) {
        var date = new Date();
        date.setTime(date.getTime()+(minutes*60*1000));
        var expires = "; expires="+date.toGMTString();
    }
    else var expires = "";
    document.cookie = name+"="+value+expires+"; path=/";
}

function readCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for(var i=0;i < ca.length;i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1,c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
}

function eraseCookie(name) {
    createCookie(name,"",-1);
}
jQuery(document).ready(function() {	

	var hide_wf_enquiry_form = readCookie('hide_wf_enquiry_form')
	if (!hide_wf_enquiry_form) {
		createCookie('hide_wf_enquiry_form','true',<?php echo Mage::getStoreConfig('webfrnd_quickcontact_options/general/autoload_after'); ?>);
	    jQuery('a[name=modal]').trigger('click');
	}

});

	setInterval(function(){ createCookie('hide_wf_enquiry_form','true',<?php echo Mage::getStoreConfig('webfrnd_quickcontact_options/general/autoload_after'); ?>); jQuery('a[name=modal]').trigger('click'); }, <?php echo Mage::getStoreConfig('webfrnd_quickcontact_options/general/autoload_after'); ?>*60*1000);

</script>
<?php endif; ?>



<style>
#mask {
  position:fixed;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}
  
#modalwindow .window {
  position:absolute;
  left:0;
  top:0;
  display:none;
  z-index:9999;
}

#modalwindow .dialog_content {
  padding:20px;
}

#modalwindow #dialog {
  background-color: #FFF;
  min-width:500px;
}
.docklink{
  <?php if (Mage::getStoreConfig('webfrnd_quickcontact_options/general/display_form')) :?>
	  display: block;
  <?php else : ?>
  display: none;
  <?php endif; ?>
  height: 15px;
  padding: 30px 43px 84px 0;
  background:url('<?php echo $this->getSkinUrl('webfrnd/quickcontact/images/btn_feedback.png')?>') no-repeat;
}
.bo_docklink a:hover{
  background:url('<?php echo $this->getSkinUrl('webfrnd/quickcontact/images/btn_feedback_hover.png')?>') no-repeat;
  padding-right: 50px;
}
</style>
<link type="text/css" href="<?php echo $this->getSkinUrl('webfrnd/quickcontact/css/form-contact.css') ?>" rel="stylesheet">

<div style="display:none;"><img src="<?php echo $this->getSkinUrl('webfrnd/quickcontact/images/btn_feedback_hover.png')?>"></div>
<div style="position:fixed; left:0px; top:200px;" class="bo_docklink"><a class="docklink" href="#dialog" name="modal"></a></div>


<div id="modalwindow">  
	
	<div id="dialog" class="window">
    	<a href="#" class="close"><img src="<?php echo $this->getSkinUrl('webfrnd/quickcontact/images/close.jpg')?>" /></a>	

		<div class="form-quick-contact" style="<?php echo !empty($bg_image) ? "background:url('{$bg_image}') no-repeat scroll 0 0 / {$popup_width} {$popup_height} rgba(0, 0, 0, 0);" : ''; ?> width:<?php echo $popup_width ;?>; height:<?php echo $popup_height ;?>;" >

		<?php if (Mage::getStoreConfig('webfrnd_quickcontact_options/general/display_form')) :?>

        <div style="padding-right:30px;padding-left:<?php echo $form_left_margin; ?>; padding-top: <?php echo $form_top_margin; ?>">
		<?php if(empty($bg_image)) : ?><div class="title" style="padding-bottom:30px;"><h1 id="quick_contact_title">Contact Us</h1></div><?php endif; ?>
		<form action="<?php echo $this->getUrl('wf_quickcontact/index/post'); ?>" method="post" name="contactform" id="contactform">
				
				<div class="text"> 
					<div class="info-txt"> <?php echo Mage::helper('quickcontact')->__('Your Name')?> <span style="color:#ff0000;">*</span></div>
					<div class="info-txt"> <?php echo Mage::helper('quickcontact')->__('Your Email')?> <span style="color:#ff0000;">*</span></div>
					<div class="info-txt"> <?php echo Mage::helper('quickcontact')->__('Your Phone')?> </div>
				</div>
								
				<div class="input">
					<input class="input-text textbox" value="<?php if(Mage::helper('customer')->isLoggedIn()) echo Mage::getSingleton('customer/session', array('name'=>'frontend'))->getCustomer()->getName()?>" type="text" name="name" id="name"/>
					<input class="input-text textbox" value="<?php if(Mage::helper('customer')->isLoggedIn()) echo Mage::getSingleton('customer/session', array('name'=>'frontend'))->getCustomer()->getEmail()?>" type="text" name="email" id="email"/>
					<input class="input-text textbox" type="text" name="telephone" id="telephone" value=""/>			
				</div>
				<div style="clear:both"><span></span></div>
				<div class="text-area">
					<p class="hm_content"><?php echo Mage::helper('quickcontact')->__('Comment')?> <span style="color:#ff0000;">*</span></p>
					<textarea name="comment" id="comment" class="input-text" rows="10" cols="64"></textarea>      
				</div>
					
				<div class="submit">                
                	<input id="submit" type="image" src="<?php echo $this->getSkinUrl('webfrnd/quickcontact/images/submit.jpg')?>">
                </div>  
				
		</form>
        </div>
        
        <?php endif; ?>
        
		</div>
	
	</div>
	<div id="mask"></div>
	
	
</div>




<?php endif; ?>